version: '2'

services:
  web: # main haystack application
    build: 
      context: web
      args:
        - NODE_ENV=${NODE_ENV}
    image: ${WEB_REGISTRY_URI}:latest
    ports:
     - "80:80"
     - "29043:29043"
    environment:
     - AWS_ACCESS_KEY_ID
     - AWS_SECRET_ACCESS_KEY
     - JOB_QUEUE_URL=http://goaws:4100/queue/local-queue1
     - MONGO_URL=mongodb://mongo:27017/
     - NODE_ENV=${NODE_ENV}
    links:
      - goaws
      #- mongo

  goaws:
    image: pafortin/goaws
    ports:
      - "4100:4100"

  worker:
    build: worker
    image: ${WORKER_REGISTRY_URI}:latest
    environment:
     - AWS_ACCESS_KEY_ID
     - AWS_SECRET_ACCESS_KEY
     - JOB_QUEUE_URL=http://goaws:4100/queue/local-queue1
     - MONGO_URL=mongodb://mongo:27017/
     - MONGO_DB_NAME=admin
     - LOGLEVEL=INFO
    links:
      - goaws

  mongo:
    image: mongo
    ports:
      - "27017:27017"
