version: '2'

services:
  web: # main haystack application
    build: web
    image: 431265468707.dkr.ecr.us-west-1.amazonaws.com/alfalfa_web:latest
    ports:
     - "3000:3000"
    environment:
     - AWS_ACCESS_KEY_ID
     - AWS_SECRET_ACCESS_KEY
     - JOB_QUEUE_URL=http://goaws:4100/queue/local-queue1
    links:
      - goaws

  goaws:
    image: pafortin/goaws
    ports:
      - "4100:4100"

  worker:
    build: worker
    image: 431265468707.dkr.ecr.us-west-1.amazonaws.com/alfalfa_worker:latest
    environment:
     - AWS_ACCESS_KEY_ID
     - AWS_SECRET_ACCESS_KEY
     - JOB_QUEUE_URL=http://goaws:4100/queue/local-queue1
    links:
      - goaws
